# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87063034658d44010b973aaef06e9a9b996a9b39ac240b984fe60d866507b083844cc86574f79ed3cc42e95e0dbeb63f9394491cc78428ec69a5a395033cc377

test:
  secret_key_base: d309a4202f4f0244994f222a53c0e84323ee8b59f4895ae9ef3192540484c11ecda81490efcc2c342864bc36e7a1f3bea0c7d6ba28aba34da6b3a38443f66bfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
